meta_product_name: "Bookids"
meta_title: "Bookids - Help your child develop through customized stories."
meta_description: "Customized books to help your child overcome challenges they experience growing up such as making friends, eating healthy and getting enough sleep."
meta_image: "swim.png"
# twitter_account: '@bookids'
